### ISSUE TITLE
Statement of contributions

### ISSUE THREAD

**Issue by weerox** [will-berg/assignment2#94]
Write statement of contributions in the README

**Comment by will-berg** [comment]
Worked on ci_server control flow, file operations, and pipeline functions. Also worked on documentation with Pydoc.

**Comment by salome-voltz** [comment]
Worked on ci_server control flow, set up the tests, listing of the builds and Essence report

**Comment by weerox** [comment]
Mainly worked on the auto updater and shell scripts and operated the server running the software.

**Comment by weerox** [comment]
Peter: Worked on the web service, some documentation and helped with process spawning and killing.

**Comment by filippaleuckfeld** [comment]
Worked on the GitHub status API. Also worked on writing all outputs to file.
