### ISSUE TITLE
Essence/Way of working

### ISSUE THREAD

**Issue by weerox** [will-berg/assignment2#95]

**Comment by salome-voltz** [comment]
[Continuous_Integration___Report.pdf](https://github.com/will-berg/assignment2/files/10707088/Continuous_Integration___Report.pdf)

**Comment by weerox** [comment]
That looks good, I agree on the state we are in. From a GitHub perspective, this assignment was a lot more fluid.

**Comment by salome-voltz** [comment]
Ok, I'm going to close the issue then. Should I hand in the report so we don't forget ?

**Comment by weerox** [comment]
It doesn't seem like we can hand in the report on Canvas, it only accepts a link. I'll add it to the repo instead
